"""initial migration

Revision ID: b46c8e4bab93
Revises: 
Create Date: 2025-11-30 02:51:47.155242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46c8e4bab93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index('idx_user_status', 'users', ['login'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('preview', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_id'), 'flat', ['id'], unique=False)
    op.create_index('user_id_for_flat', 'flat', ['user_id'], unique=False)
    op.create_table('session',
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('flat_for_photo', 'photo', ['flat_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('flat_for_report', 'report', ['flat_id'], unique=False)
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_table('report_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_part_id'), 'report_part', ['id'], unique=False)
    op.create_index('report_for_photo_report', 'report_part', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('report_for_photo_report', table_name='report_part')
    op.drop_index(op.f('ix_report_part_id'), table_name='report_part')
    op.drop_table('report_part')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_index('flat_for_report', table_name='report')
    op.drop_table('report')
    op.drop_index('flat_for_photo', table_name='photo')
    op.drop_table('photo')
    op.drop_table('session')
    op.drop_index('user_id_for_flat', table_name='flat')
    op.drop_index(op.f('ix_flat_id'), table_name='flat')
    op.drop_table('flat')
    op.drop_index('idx_user_status', table_name='users', postgresql_where=sa.text('is_active = true'))
    op.drop_table('users')
    # ### end Alembic commands ###
